config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:edit, :update] do
    get 'delete' => 'users#destroy', as: 'destroy'
  end

  get 'home' => 'static#home', as: :home

  root 'static#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :proteges, class_name: 'User', foreign_key: 'sponsor_id'
  belongs_to :sponsor, class_name: 'User'

  validates_presence_of :login, :last_name, :first_name
  validates_uniqueness_of :login

  def self.with_no_proteges
    self.joins('LEFT JOIN users proteges ON proteges.sponsor_id = users.id').where('proteges.ID IS null')
  end

  # Do not use #size on this because it creates a SQL error. #length loads the query and returns expected result
  # This is because of the #group clause
  def self.with_more_than_x_proteges(x)
    self.joins('LEFT JOIN users proteges ON proteges.sponsor_id = users.id').group(:id)
        .having('COUNT(proteges.id) > ?', x)
  end

  def full_name
    "#{self.last_name} #{self.first_name}"
  end

  # Do not use #size on this because it creates a SQL error. #length loads the query and returns expected result
  # This is because of the #group clause
  def self.who_sponsored_most_people(max_number_of_sponsors)
    self.joins('LEFT JOIN users proteges ON proteges.sponsor_id = users.id').group(:id)
        .order('COUNT(proteges.id) DESC').limit(max_number_of_sponsors)
  end

  def self.order_by_people_sponsoring(order_direction = 'ASC')
    self.joins('LEFT JOIN users proteges ON proteges.sponsor_id = users.id').group(:id)
        .order("COUNT(proteges.id) #{order_direction}")
  end

  def delete_with_responsoring
    self.proteges.find_each { |protege| protege.update(sponsor: self.sponsor) }
    self.destroy
  end

  def initial_sponsor
    self.sponsor.nil? ? self : self.sponsor.initial_sponsor
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = I18n.default_locale
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users =
        if params[:sort] == 'proteges_count'
          User.order_by_people_sponsoring(get_order_direction)
        else
          User.all
        end

    # @users = @users.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:login, :first_name, :last_name, :sponsor_id))

    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user, notice: 'User created successfully'
        end
      else
        format.html do
          render action: :new
        end
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id] || params[:id])

    if request.delete?
      @user.delete_with_responsoring
      redirect_to users_path, notice: "User #{@user.login} has been deleted."
    end
  end

  private
  def get_order_direction
    params[:order].nil? || params[:order] == 'ASC' ? 'ASC' : 'DESC'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def users_to_login_as_links(users)
    users.map { |user| link_to(user.login, user) }.join(', ').html_safe
  end

  def sponsor_full_name_as_link(user)
    user.sponsor.nil? ? '-' : user_as_link(user.sponsor)
  end

  def make_sponsoring_tree_for_users
    root_user = User.first
    make_sponsoring_tree_for_user(root_user)
  end

  def make_sponsoring_tree_for_user(user)
    content_tag('ul') do
      content = content_tag('li', user_as_link(user))
      user.proteges.each { |protege| content += make_sponsoring_tree_for_user(protege) } if user.proteges.any?
      content
    end
  end

  def reverse_order
    if params[:order].nil? || params[:order] == 'DESC'
      'ASC'
    else
      'DESC'
    end
  end

  def user_as_link(user)
    link_to(user.full_name, user)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parrainages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/destroy.html.erb
<h1>Destroy <%= @user.full_name %>?</h1>
<div>
  <%= button_to('Yes', @user, method: :delete) %>
  <%= button_to('No', @user, method: :get) %>
</div>

app/views/users/index.html.erb
<h1>User list</h1>
<div>
  <%= button_to('Create a user', new_user_path, method: :get) %>
</div>
<table>
  <thead>
  <tr>
    <th>Login</th>
    <th>Full name</th>
    <th>Sponsored by</th>
    <th><%= link_to 'Proteges number', users_path(sort: :proteges_count, order: reverse_order ) %></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.full_name %></td>
        <td><%= sponsor_full_name_as_link(user) %></td>
        <td><%= link_to(user.proteges.count, user) %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<h2>Sponsoring tree</h2>
<%= make_sponsoring_tree_for_users %>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= form_for(@user) do |form| %>
    <%= form.label(:login) %>
    <%= form.text_field(:login) %><br />

    <%= form.label(:last_name) %>
    <%= form.text_field(:last_name) %><br />

    <%= form.label(:first_name) %>
    <%= form.text_field(:first_name) %><br />

    <%= form.label(:sponsor) %>
    <%= form.collection_select(:sponsor_id, User.all, :id, :full_name) %><br />

    <%= form.submit %>
<% end %>
<div>
  <%= link_to 'Back to user list', users_path %>
</div>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<ul>
  <li>login: <%= @user.login %></li>
  <li>Created at: <%= @user.created_at %></li>
  <li>Updated at: <%= @user.updated_at %></li>
  <li>Sponsor: <%= sponsor_full_name_as_link(@user) %></li>
  <li>Initial sponsor: <%= user_as_link(@user.initial_sponsor) %></li>
</ul>
<h2>Sponsoring tree</h2>
<%= make_sponsoring_tree_for_user(@user) %>
<div>
  <%= link_to('Back to user list', users_path) %>
  <%= button_to('Delete', user_destroy_url(@user), method: :get) %>
</div>